### ISSUE TITLE
Installation of livecd-tools on RHEL6.4

### ISSUE THREAD

**Issue by jagipson** [rhinstaller/livecd-tools#10]
livecd-tools broken on RHEL 6.4.

steps to reproduce:

cd /tmp
unzip livecd-tools-master.zip
cd livecd-tools-master
make install
livecd-creator

Traceback (most recent call last):
  File "/usr/bin/livecd-creator", line 241, in <module>
    hack = do_nss_sss_hack()
  File "/usr/bin/livecd-creator", line 236, in do_nss_sss_hack
    hack = forgettable._dlopen('libnss_sss.so.2')
OSError: libnss_sss.so.2: cannot open shared object file: No such file or directory

I have verified that the sssd package is installed.

**Comment by jagipson** [comment]
It appears to run fine if using the rhel6 branch instead of master
