### ISSUE TITLE
Unable to unmount filesystem

### ISSUE THREAD

**Issue by Jasonsen** [rhinstaller/livecd-tools#252]
OS is Rocky linux 8
livecd-tools version is 31.0-1.el8
use command create a livecd

LANG=C livecd-creator -c /home/Purescue/Pure.ks --cache=/home/Purescue/livecd/cache --tmpdir=/home/Purescue/livecd/tmp --fslabel=Rescue-Tool -d

after that, it will return following errors:                       
Error creating Live CD : Unable to unmount filesystem at /home/Purescue/livecd/tmp/imgcreate-m9bd_c6q/install_root/var/cache/dnf. The process using the imgcreate module, or one of the libraries used by that process, leaked a reference to the filesystem. Please report a bug at <https://github.com/livecd-tools/livecd-tools/issues>.

how can i solve this issue?

**Comment by Grokzen** [comment]
We have the exact same issue

```
rror creating Live CD : Unable to unmount filesystem at /var/tmp/imgcreate-y7d1s1lx/install_root/var/cache/dnf. The process using the imgcreate module, or one of the libr
aries used by that process, leaked a reference to the filesystem. Please report a bug at <https://github.com/livecd-tools/livecd-tools/issues>.
umount: /var/tmp/imgcreate-y7d1s1lx/install_root/sys/fs/selinux/load: not mounted.
Traceback (most recent call last):
  File "/bin/livecd-creator", line 265, in <module>
    sys.exit(main())
  File "/bin/livecd-creator", line 252, in main
    creator.cleanup()
  File "/usr/lib/python3.6/site-packages/imgcreate/creator.py", line 613, in cleanup
    self.unmount()
  File "/usr/lib/python3.6/site-packages/imgcreate/creator.py", line 585, in unmount
    self._undo_bindmounts()
  File "/usr/lib/python3.6/site-packages/imgcreate/creator.py", line 355, in _undo_bindmounts
    b.unmount()
  File "/usr/lib/python3.6/site-packages/imgcreate/fs.py", line 1065, in unmount
    raise MountError(umount_fail_fmt % self.dest)
imgcreate.errors.MountError: Unable to unmount filesystem at /var/tmp/imgcreate-y7d1s1lx/install_root/sys. The process using the imgcreate module, or one of the libraries 
used by that process, leaked a reference to the filesystem. Please report a bug at <https://github.com/livecd-tools/livecd-tools/issues>.
Unmounting directory /var/tmp/imgcreate-y7d1s1lx/install_root
Losetup remove /dev/loop0
```

We are using the following livecd-tools version `livecd-tools-31.0-1.el8.x86_64` running on a bento/centos-8 vagrant box
